-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 00:33:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema family_food
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema family_food
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `family_food` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `family_food` ;

-- -----------------------------------------------------
-- Table `family_food`.`diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_food`.`diet` (
  `diet_id` INT(11) NOT NULL,
  `Diet_name` VARCHAR(30) NULL DEFAULT NULL,
  `Number_of_meals` INT(11) NULL DEFAULT NULL,
  `fname` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`diet_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_food`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_food`.`menu` (
  `menu_id` INT(11) NOT NULL,
  `Menu_name` VARCHAR(30) NULL DEFAULT NULL,
  `Menu_type` VARCHAR(30) NULL DEFAULT NULL,
  `Variety` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_food`.`diet_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_food`.`diet_menu` (
  `diet_menu_id` INT(11) NOT NULL,
  `diet_id` INT(11) NULL DEFAULT NULL,
  `menu_id` INT(11) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`diet_menu_id`),
  INDEX `diet_id` (`diet_id` ASC),
  INDEX `menu_id` (`menu_id` ASC),
  CONSTRAINT `diet_menu_ibfk_1`
    FOREIGN KEY (`diet_id`)
    REFERENCES `family_food`.`diet` (`diet_id`),
  CONSTRAINT `diet_menu_ibfk_2`
    FOREIGN KEY (`menu_id`)
    REFERENCES `family_food`.`menu` (`menu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_food`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_food`.`products` (
  `product_id` INT(11) NOT NULL,
  `Product_name` VARCHAR(30) NULL DEFAULT NULL,
  `Calories` INT(11) NULL DEFAULT NULL,
  `PFC` INT(11) NULL DEFAULT NULL,
  `Proteins` INT(11) NULL DEFAULT NULL,
  `Fats` INT(11) NULL DEFAULT NULL,
  `Carbohydrates` INT(11) NULL DEFAULT NULL,
  `Category` VARCHAR(30) NULL DEFAULT NULL,
  `Weight` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_food`.`product_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_food`.`product_menu` (
  `product_menu_id` INT(11) NOT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `menu_id` INT(11) NULL DEFAULT NULL,
  `quantify` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`product_menu_id`),
  INDEX `product_id` (`product_id` ASC),
  INDEX `munu_id` (`menu_id` ASC),
  CONSTRAINT `product_menu_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `family_food`.`products` (`product_id`),
  CONSTRAINT `product_menu_ibfk_2`
    FOREIGN KEY (`menu_id`)
    REFERENCES `family_food`.`menu` (`menu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_food`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_food`.`user` (
  `user_id` INT(11) NOT NULL,
  `User_name` VARCHAR(30) NULL DEFAULT NULL,
  `Gender` VARCHAR(30) NULL DEFAULT NULL,
  `Age` INT(11) NULL DEFAULT NULL,
  `Date_of_birth` DATE NULL DEFAULT NULL,
  `Height` INT(11) NULL DEFAULT NULL,
  `Weight` INT(11) NULL DEFAULT NULL,
  `Activity_level` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_food`.`user_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_food`.`user_diet` (
  `user_diet_id` INT(11) NOT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `diet_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_diet_id`),
  INDEX `user_id` (`user_id` ASC),
  INDEX `diet_id` (`diet_id` ASC),
  CONSTRAINT `user_diet_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `family_food`.`user` (`user_id`),
  CONSTRAINT `user_diet_ibfk_2`
    FOREIGN KEY (`diet_id`)
    REFERENCES `family_food`.`diet` (`diet_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
